<a href="https://colab.research.google.com/github/tshimizu8/MachineLearning_CheatSheet/blob/master/0010_Vector_Matrix_List.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 機械学習チートシート（ベクトル、行列、Python）

Python による **機械学習** に向けて、プログラミングメモを作成しています。  　　

### 環境、ライブラリ

In [0]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(seed=0) # 乱数の種を指定
!python -V

Python 3.6.9


### データの作成

###### ベクトル　vector

In [0]:
l= [0, 1] # リスト   list.shapeは無い
v = np.array(l) # ベクトル化 vector、形状(2) np.array()
v12 = v.reshape((1, -1)) # 行ベクトル化、形状(1,2) Row vector　
v21 = v.reshape((-1, 1)) # 列ベクトル化、形状(2,1) Column vector　
print((list, v, v12, v21, v.shape, v12.shape, v21.shape))
print(v.tolist(), v12.tolist(), v21.tolist()) # リスト化 tolist()
vf = v.flatten() # flatten() -> ベクトル化
v12f = v12.flatten()
v21f = v21.flatten()
print([vf ,v12f ,v21f ,vf.shape, v12f.shape, v21f.shape])

(<class 'list'>, array([0, 1]), array([[0, 1]]), array([[0],
       [1]]), (2,), (1, 2), (2, 1))
[0, 1] [[0, 1]] [[0], [1]]
[array([0, 1]), array([0, 1]), array([0, 1]), (2,), (2,), (2,)]


In [0]:
a = np.arange(2) # 要素の取り出し
b = np.arange(2).reshape((1, 2)) # 行ベクトル Row vector
c = np.arange(2).reshape((2, 1)) # 列ベクトル Column vector 
(a[0] ,b[0] ,c[0], a[1], b[0,1], c[1,0], a.shape, b.shape, c.shape)

(0, array([0, 1]), array([0]), 1, 1, 1, (2,), (1, 2), (2, 1))

In [0]:
a = np.array([])   # 空 行ベクトル  どちらも　array([])
b = np.array([[]]) # 空 列ベクトル
(a, a.shape, a.tolist(), b, b.shape, b.tolist())

(array([], dtype=float64),
 (0,),
 [],
 array([], shape=(1, 0), dtype=float64),
 (1, 0),
 [[]])

In [0]:
a = np.array([0] * 2)   # ゼロ　行ベクトル
b = np.array([[0]] * 2) # ゼロ　列ベクトル
(a, a.shape, b, b.shape)

(array([0, 0]), (2,), array([[0],
        [0]]), (2, 1))

In [0]:
a = np.array([0, 1] * 2) # 繰り返し
b = np.array([[0, 1]] * 2) # 行ベクトル
c = np.array([[0],[1]] * 2) # 列ベクトル
(a, b, c, a.shape, b.shape, c.shape)

(array([0, 1, 0, 1]), array([[0, 1],
        [0, 1]]), array([[0],
        [1],
        [0],
        [1]]), (4,), (2, 2), (4, 1))

In [0]:
np.concatenate([np.array([0] * 3) ,np.array([1] * 3)]) # ベクトルの結合

array([0, 0, 0, 1, 1, 1])

In [0]:
a = np.arange(2).reshape((1, -1)) # 形状の推測 １つの次元だけ －１ を指定して、推測指定ができる
b = np.arange(2).reshape((-1, 1))
(a,b)

(array([[0, 1]]), array([[0],
        [1]]))

In [0]:
a = np.array([0,1]) # arrayのネスト
b = np.array(a) # 何も起きない
c = np.array([a])
(a, b, c, a.shape, b.shape, c.shape)

(array([0, 1]), array([0, 1]), array([[0, 1]]), (2,), (2,), (1, 2))

In [0]:
np.random.seed(seed=32) # 乱数　Seed有り
(np.random.randint(0, 2, 5), np.random.randint(0,10,10)) 

(array([1, 1, 1, 0, 0]), array([8, 3, 7, 9, 3, 5, 9, 4, 1, 3]))

In [0]:
np.random.seed(seed=None) # 乱数　Seed無し
(np.random.randint(0, 2, 5), np.random.randint(0,10,10))

(array([0, 0, 1, 1, 0]), array([6, 3, 7, 6, 7, 0, 7, 3, 5, 2]))

In [0]:
np.sin(np.linspace(0, np.pi, 4)) # sinデータ

array([0.00000000e+00, 8.66025404e-01, 8.66025404e-01, 1.22464680e-16])

In [0]:
a = np.arange(5) # clip()　上下値制限
np.clip(a, 1, 3)

array([1, 1, 2, 3, 3])

In [0]:
a = np.array([1.2, 2.6]) # 型変換　 float -> int
b = np.round(a).astype(np.int32)
(b, a.dtype, b.dtype)

(array([1, 3], dtype=int32), dtype('float64'), dtype('int32'))

In [0]:
a = np.arange(3).reshape(1,-1) # 行ベクトルの１つ取り出しは、リスト[]でなくarray[]になる。　
b = a[0]
print((a, b, a.shape, b.shape))
a = np.arange(3).reshape(-1,1) # 列ベクトルの１つ取り出しは、リスト[]でなくarray[]になる。　
b = a[0]
print((a, b, a.shape, b.shape))

(array([[0, 1, 2]]), array([0, 1, 2]), (1, 3), (3,))
(array([[0],
       [1],
       [2]]), array([0]), (3, 1), (1,))


In [0]:
a = np.array([[1]]) # flatten 動作確認  外側の[]が１つ削除されるのみ
b = a.flatten()
(a, a.shape, b, b.shape)

(array([[1]]), (1, 1), array([1]), (1,))

In [0]:
fn1 = lambda x: 2 * x + 1 # 関数適用 制限有り　積和はOK、論理はNG  
fn2 = lambda x: 7 if 0 == x else 77 
v = np.arange(2).reshape((2, 1))
# fn2(v) ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
fn2v = np.array(list(map(fn2,v))) # 動きが不安定、カーネルリセットが必要。
(fn1(v),fn2v)

(array([[1],
        [3]]), array([ 7, 77]))

###### 行列　matrix

In [0]:
np.arange(6).reshape((3, 2)) # 配列、matrix

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
a = np.arange(4).reshape(2,2) # in 取り出し
(a[0], a[1])

(array([0, 1]), array([2, 3]))

In [0]:
 2 * np.identity(2) * 3 # 単位行列、identity matrix

array([[6., 0.],
       [0., 6.]])

In [0]:
x = np.arange(4).reshape((2, 2)) # zero行列 like
(np.zeros([2, 3]), np.zeros_like(x))

(array([[0., 0., 0.],
        [0., 0., 0.]]), array([[0, 0],
        [0, 0]]))

In [0]:
a = np.arange(4 * 4).reshape((4, 4)) # 配列の切り出し
b = a[1:3,1:3]
(a,b)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]), array([[ 5,  6],
        [ 9, 10]]))

### ベクトル、行列の四則演算 +-*/（Four arithmetic operations）

In [0]:
v = np.arange(4).reshape((2, 2))
2 * v * 5 # スカラー積 

array([[ 0, 10],
       [20, 30]])

In [0]:
a =np.arange(4) + np.arange(4) # 和
b = np.arange(4)
b += np.arange(4)
(a, b)

(array([0, 2, 4, 6]), array([0, 2, 4, 6]))

In [0]:
v = np.arange(4).reshape((2, 2)) #積　(単なる要素どうしの積)
v * v

array([[0, 1],
       [4, 9]])

In [0]:
v = np.array([0, 1]) # ブロードキャスト　-> [[0, 1],[0, 1]]
m = np.arange(4).reshape((2, 2))
(v * m , m * v) # (ベクトル * 行列、 行列 * ベクトル)

(array([[0, 1],
        [0, 3]]), array([[0, 1],
        [0, 3]]))

### ベクトル演算（Vector operation）

In [0]:
a = np.array([[1, 2]]) # 内積、inner product
(np.inner(a,a), a@a.T)

(array([[5]]), array([[5]]))

In [0]:
a = np.array([[1, 2]]) # 外積、直積、outer product、vector product、direct product、tensor product
(np.outer(a,a),  a.T@a)

(array([[1, 2],
        [2, 4]]), array([[1, 2],
        [2, 4]]))

In [0]:
v = np.array([1, 1]) # 長さ、ノルム0,1,2、norm、https://ja.wikipedia.org/wiki/ノルム
(np.linalg.norm(v), np.linalg.norm(v, ord=0), np.linalg.norm(v, ord=1), np.linalg.norm(v, ord=2)) 

(1.4142135623730951, 2.0, 2.0, 1.4142135623730951)

In [0]:
v1 = np.array([1, 0]) # cos類似度、cos similarity、コサイン距離、https://ja.wikipedia.org/wiki/ベクトルのなす角
v2 = v1
np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)) 

1.0

### 行列演算（Matrix operation）

In [0]:
np.arange(6).reshape((2, 3)).T # 転置行列、 transposed matrix

array([[0, 3],
       [1, 4],
       [2, 5]])

In [0]:
m = np.array([[0, 1], [2, 3]]) # m@v 行列ベクトル積 
v = np.array([0, 1]) 
(m @ v, np.dot(m,v), v @ m, np.dot(v,m))

(array([1, 3]), array([1, 3]), array([2, 3]), array([2, 3]))

In [0]:
v = np.array([[0,1]]) # v@m  ベクトル行列積 = [2, 3]  ２入力(1,2)@入力重み(2,2)(2ノード)
m = np.array([[0, 1], [2, 3]])
(v @ m, v, m, v.shape, m.shape)

(array([[2, 3]]), array([[0, 1]]), array([[0, 1],
        [2, 3]]), (1, 2), (2, 2))

In [0]:
a = np.array([[0, 1], [2, 3]]) # 行列積、matrix product、array([[ 2,  3],[ 6, 11]])　　
a @ a

array([[ 2,  3],
       [ 6, 11]])

In [0]:
v = np.array([2]) # ??
vr = np.array([[1, 2]])
v @ vr

array([2, 4])

In [0]:
m1 = np.array([[1, 0], [0, 2]]) # 逆行列　　m1@m2 = I
m2 = np.array([[1, 0], [0, 0.5]]) # = https://ja.wikipedia.org/wiki/正則行列
(np.linalg.inv(m1), np.linalg.inv(m2), m1*m2, m2*m1)

(array([[1. , 0. ],
        [0. , 0.5]]), array([[1., 0.],
        [0., 2.]]), array([[1., 0.],
        [0., 1.]]), array([[1., 0.],
        [0., 1.]]))

In [0]:
from scipy import linalg # 固有値　eigenvalue
# linalg.eigvals()
# Ax = λx を満たす零でないベクトル x とスカラー λ が存在するとき、x を A の固有ベクトル（右固有ベクトル）、λ を A の固有値と呼ぶ
# https://www.programcreek.com/python/example/62154/numpy.linalg.eigvals

### リスト操作

In [0]:
[7] * 3 # 繰り返し

[7, 7, 7]

In [0]:
[0, 1, 2][0] # 最初の要素

0

In [0]:
[0, 1, 2][-1] # 最後の要素

2

In [0]:
[0, 1, 2][-2] # 最後から２番目の要素

1

In [0]:
len([0, 1, 2]) # 要素数

3

In [0]:
a = [0, 1] + [2, 3] # 結合
b = [[0], [1], [2]] + [[0]]*3
(a, b)

([0, 1, 2, 3], [[0], [1], [2], [0], [0], [0]])

In [0]:
list(zip([0, 1] ,[2, 3])) # zip

[(0, 2), (1, 3)]

In [0]:
[x + y for (x, y) in zip([0, 1] ,[2, 3])] # 要素毎の加算

[2, 4]

In [0]:
v = [0.5, 0.51] # map 
list(map(lambda x:round(x), v))

[0, 1]

### リスト　スライス

In [0]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9] # 分割
(a[:3], a[3:])

([1, 2, 3], [4, 5, 6, 7, 8, 9])

In [0]:
[1, 2, 3, 4, 5, 6, 7, 8, 9][1:] # 最初の要素以外

[2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
[1, 2, 3, 4, 5, 6, 7, 8, 9][:-1] # 最後の要素以外

[1, 2, 3, 4, 5, 6, 7, 8]

In [0]:
[1, 2, 3, 4, 5, 6, 7, 8, 9][-3:] # 後ろの部分

[7, 8, 9]

In [0]:
[1, 2, 3, 4, 5, 6, 7, 8, 9][:3] # 前の部分

[1, 2, 3]

In [0]:
[1, 2, 3, 4, 5, 6, 7, 8, 9][1:7] # 途中の部分

[2, 3, 4, 5, 6, 7]

In [0]:
[1, 2, 3, 4, 5, 6, 7, 8, 9][1:-1] # 途中の部分

[2, 3, 4, 5, 6, 7, 8]

In [0]:
[1, 2, 3, 4, 5, 6, 7, 8, 9][1:7:2] # 2つ置き

[2, 4, 6]

In [0]:
[1, 2, 3, 4, 5, 6, 7, 8, 9][::-1] # 逆順

[9, 8, 7, 6, 5, 4, 3, 2, 1]

### OS

In [0]:
import os # ディレクトリ、リスト、コピー
import shutil
os.getcwd()
# os.listdir(outDir)
# shutil.copy (fromFile, toFile) 
# os.makedirs(new_dir_path_recursive, exist_ok=True)    深い階層のディレクトリまで再帰的に作成

'/content'

In [0]:
# a = input('x y:') # プロンプト付きキー入力   12 34
# b = a.split()
# c = list(map(lambda x: int(x), b))
# [a,b,c] #  ['12 34', ['12', '34'], [12, 34]]

In [0]:
import datetime # 現在時刻
print(datetime.datetime.now())
datetime.datetime.now()

2019-12-25 18:28:23.946902


datetime.datetime(2019, 12, 25, 18, 28, 23, 948164)

### Python

In [0]:
round(1.234, 2) # 少数丸め、桁数指定

1.23

In [0]:
s = '1234' # ゼロパディング
s.zfill(8)

'00001234'

In [0]:
((1,), (2))  # 1要素のタプル　(2)は２になりNG

((1,), 2)

In [0]:
x = -3 # if 3項演算子
x if 0 < x  else 0

0

In [0]:
for i, input in enumerate([5, 6]): # index付き繰り返し
    print(i,input)
for i, input in enumerate(np.arange(2)): # numpyでも使える
    print(i,input)

0 5
1 6
0 0
1 1


In [0]:
global Debug # グローバル変数

In [0]:
def f1(): # 局所関数定義
    def f2(): return 1
    return f2()
f1()

1

In [0]:
# while True:   Repeat-until
#     ...
#      if cond: break


In [0]:
!cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


Playground モード という編集不可なノートブック

In [0]:
from google.colab import files # Colaboratory File Upload
uploaded = files.upload()

### その他

In [0]:
def f(loop_count): # 実行時間計測
    sum = 0
    for i in range(loop_count):
        sum += i
    print ("sum", sum)
%time f(100000)

sum 4999950000
CPU times: user 7.85 ms, sys: 170 µs, total: 8.02 ms
Wall time: 9.42 ms


In [0]:
v = np.array([0, 1]) # デバッグ出力
print(v1,[v1],(v1,))  # 「array()」の有無が異なる

[1 0] [array([1, 0])] (array([1, 0]),)


github https://github.com/